// This configuration option enables you to set a list of languages to be displayed in the languages drop down.
const codesample = [
  { text: 'Markup + HTML + XML + SVG + MathML + *', value: 'markup' },
  { text: 'JavaScript', value: 'javascript' },
  { text: 'ASP.NET (C#)', value: 'aspnet' },
  { text: 'Bash', value: 'bash' },
  { text: 'C', value: 'c' },
  { text: 'C#', value: 'csharp' },
  { text: 'C++', value: 'cpp' },
  { text: 'Docker', value: 'docker' },
  { text: 'Git', value: 'git' },
  { text: 'Go', value: 'go' },
  { text: 'Java', value: 'java' },
  { text: 'JSON', value: 'json' },
  { text: 'Makefile', value: 'makefile' },
  { text: 'Markdown', value: 'markdown' },
  { text: 'Nginx', value: 'nginx' },
  { text: 'Perl', value: 'perl' },
  { text: 'PHP', value: 'php' },
  { text: 'Python', value: 'Python' },
  { text: 'Ruby', value: 'Ruby' },
  { text: 'SQL', value: 'sql' },
  { text: 'Vim', value: 'vim' },
  { text: 'YAML', value: 'yaml' },
  { text: 'Apache Configuration', value: 'apacheconf' },
  { text: 'C-like', value: 'clike' },
  { text: 'CSS', value: 'css' },
  { text: 'CSS Extras', value: 'css-extras' },
  { text: 'JSONP', value: 'jsonp' },
  { text: 'PHP Extras', value: 'php-extras' },
  { text: 'PowerShell', value: 'PowerShell' },
  { text: 'R', value: 'R' },
  { text: 'React JSX', value: 'jsx' },
  { text: 'Regex', value: 'Regex' },
  { text: 'Sass (Sass)', value: 'sass' },
  { text: 'Scss (Scss)', value: 'scss' },
  { text: 'Swift', value: 'Swift' }
]
export default codesample
